# Generated by Django 5.2.8 on 2025-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='location',
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='description',
            field=models.TextField(blank=True, help_text='Opis (dla Outdoor/Office)'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='full_number',
            field=models.CharField(blank=True, help_text='Numer pełny (dla Cameleon/Condor)', max_length=128),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='location_type',
            field=models.CharField(choices=[('cameleon', 'Cameleon'), ('condor', 'Condor'), ('outdoor', 'Outdoor'), ('office', 'Office')], default='cameleon', help_text='Typ lokalizacji', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='short_number',
            field=models.CharField(blank=True, help_text='Numer skrócony (dla Cameleon/Condor)', max_length=64),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='name',
            field=models.CharField(help_text='Nazwa lokalizacji / pojazdu', max_length=255),
        ),
    ]
