# Generated by Django 5.2.8 on 2025-12-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_standardworkhours_singleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Short code', max_length=64, unique=True)),
                ('full_name', models.CharField(help_text='Full name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description')),
            ],
            options={
                'verbose_name': 'Job State',
                'verbose_name_plural': 'Job States',
                'ordering': ['short_name'],
            },
        ),
    ]
