# Generated by Django 5.2.8 on 2025-12-10 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_inventoryitem_part_description"),
        ("worklog", "0005_jobstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(help_text='Due date (YYYY-MM-DD)')),
                ('wl_number', models.CharField(editable=False, max_length=128, unique=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time', null=True)),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('part_description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours (0.25 increments)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_worklog_entries', to='inventory.inventoryitem')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklog_entries', to='worklog.jobstate')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unit')),
                ('vehicle_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklog_entries', to='worklog.vehiclelocation')),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='worklog.worklog')),
            ],
            options={
                'verbose_name': 'Work Log Entry',
                'verbose_name_plural': 'Work Log Entries',
            },
        ),
    ]
