# Generated by Django 5.2.8 on 2025-12-11 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0006_worklog_worklogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Docelowy adres e-mail do wysyłki worklogów', max_length=254)),
                ('users', models.ManyToManyField(help_text='Użytkownicy, których worklogi będą oznaczone do wysyłki', related_name='worklog_email_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worklog E-mail Rule',
                'verbose_name_plural': 'Worklog E-mail Rules',
            },
        ),
    ]
