# Generated by Django 5.2.8 on 2025-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0009_alter_editcondition_editable_time_since_created'),
        ('worklog', '0009_worklogemailsettings_send_new'),
    ]

    operations = [
    ]
