# Generated by Django 5.2.8 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0012_worklogdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
