# Generated by Django 5.2.8 on 2025-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0014_worklogentrystatechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='email_pending',
            field=models.BooleanField(default=False, help_text='If true, an e-mail send is scheduled.'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='email_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Planned send time (Kuwait).', null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the work log e-mail was actually sent.', null=True),
        ),
        migrations.AlterField(
            model_name='worklogentrystatechange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
