# Generated by Django 5.2.8 on 2025-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worklog", "0015_worklog_email_pending_worklog_email_scheduled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklogemailsettings",
            name="enable_scheduled_send",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, scheduled worklogs will not be auto-sent by the background task.",
            ),
        ),
    ]

