# Generated by Django 5.2.8 on 2025-12-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0019_vehiclelocation_sort_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editcondition',
            options={'verbose_name': 'Log Edition Condition', 'verbose_name_plural': 'Log Edition Conditions'},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': 'Work Log', 'verbose_name_plural': 'Log List'},
        ),
        migrations.AlterModelOptions(
            name='worklogemailsettings',
            options={'verbose_name': 'Log Email Rule', 'verbose_name_plural': 'Log Email Rules'},
        ),
    ]
