# Generated by Django 5.2.8 on 2025-12-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoetryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Poetry type',
                'verbose_name_plural': 'Poetry types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoetryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poetry_texts', to=settings.AUTH_USER_MODEL)),
                ('poetry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='lifemotivation.poetrytype')),
            ],
            options={
                'verbose_name': 'Poetry text',
                'verbose_name_plural': 'Poetry texts',
                'ordering': ['id'],
            },
        ),
    ]
