# Generated by Django 5.2.8 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailsettings',
            name='from_email',
            field=models.EmailField(help_text='From address (usually the same as your login)', max_length=254),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='smtp_host',
            field=models.CharField(help_text='SMTP server (e.g. Gmail: smtp.gmail.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password (Gmail: App Password from Google Account > Security > App passwords)', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP port (Gmail TLS: 587, Gmail SSL: 465)'),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='SMTP login (e.g. your full Gmail address)', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='timeout',
            field=models.PositiveIntegerField(default=30, help_text='Timeout in seconds (default 30)'),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL (Gmail: ON only with port 465; never with TLS together)'),
        ),
        migrations.AlterField(
            model_name='adminemailsettings',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS (Gmail: ON with port 587)'),
        ),
    ]
