# Generated by Django 5.2.8 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], default='import', max_length=10)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10)),
                ('source_type', models.CharField(choices=[('file', 'File (CSV/XLSX)'), ('url', 'URL'), ('db', 'Database')], default='file', max_length=10)),
                ('source_location', models.CharField(blank=True, help_text='Path/URL/DSN depending on source type.', max_length=512)),
                ('schedule', models.CharField(blank=True, help_text='Cron-like string for automatic mode.', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, help_text='Last run status/info.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Job',
                'verbose_name_plural': 'Data Jobs',
                'ordering': ['name'],
            },
        ),
    ]
