# Generated by Django 5.2.8 on 2025-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDeleteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Delete All Data Base',
                'verbose_name_plural': 'Delete All Data Base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseExportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Data Base Export',
                'verbose_name_plural': 'Data Base Export',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseRestoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Database Tools / Restore from File (Import)',
                'verbose_name_plural': 'Database Tools / Restore from File (Import)',
                'managed': False,
            },
        ),
    ]
