# Generated by Django 5.2.8 on 2025-11-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.IntegerField()),
                ('shelf', models.CharField(max_length=1)),
                ('box', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=100, verbose_name='Group')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('part_description', models.CharField(max_length=255, verbose_name='Part Description')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Part Number')),
                ('dcm_number', models.CharField(blank=True, max_length=100, verbose_name='DCM NUMBER')),
                ('oem_name', models.CharField(blank=True, max_length=100, verbose_name='OEM Name')),
                ('oem_number', models.CharField(blank=True, max_length=100, verbose_name='OEM Number')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Vendor')),
                ('source_location', models.CharField(blank=True, max_length=100, verbose_name='Source Location')),
                ('units', models.CharField(blank=True, max_length=50, verbose_name='Units')),
                ('quantity_in_stock', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Stock')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('reorder_level', models.IntegerField(blank=True, null=True, verbose_name='Reorder Level')),
                ('reorder_time_days', models.IntegerField(blank=True, null=True, verbose_name='Reorder Time in Days')),
                ('quantity_in_reorder', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Reorder')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Discontinued?')),
            ],
            options={
                'ordering': ['rack', 'shelf', 'box'],
            },
        ),
    ]
