# Generated by Django 5.2.8 on 2025-11-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('dcm_number', 'DCM NUMBER'), ('oem_name', 'OEM Name'), ('oem_number', 'OEM Number'), ('vendor', 'Vendor'), ('source_location', 'Source Location'), ('price', 'Price'), ('reorder_level', 'Reorder Level'), ('reorder_time_days', 'Reorder Time in Days'), ('quantity_in_reorder', 'Quantity in Reorder'), ('discontinued', 'Discontinued?')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryImportExport',
            fields=[
            ],
            options={
                'verbose_name': 'Import/Export',
                'verbose_name_plural': 'Import/Export',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventoryitem',),
        ),
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_columns', models.ManyToManyField(blank=True, help_text='Columns visible only for purchase admin. Others are visible for everyone.', to='inventory.inventorycolumn')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
