# Generated by Django 5.2.8 on 2025-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemgroup_inventoryitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='condition_status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('USED_OK', 'USED / OK'), ('USED_NOK', 'USED / NOK'), ('INCOMPLETE', 'INCOMPLETE'), ('UNKNOWN', 'UNKNOWN'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='Condition Status'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='Needs verification?'),
        ),
    ]
