# Generated by Django 5.2.8 on 2025-11-29 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_condition_status_inventoryitem_verify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUserMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_color', models.CharField(choices=[('NONE', 'None'), ('RED', 'Red'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('BLUE', 'Blue')], default='NONE', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='User note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory user meta',
                'verbose_name_plural': 'Inventory user meta',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
