# Generated by Django 5.2.8 on 2025-11-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryusermeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycolumn',
            name='full_label',
            field=models.CharField(blank=True, help_text='Full column name for tooltips / lollipops. If empty, the default human-readable name from FIELD_CHOICES is used.', max_length=128),
        ),
        migrations.AddField(
            model_name='inventorycolumn',
            name='functional_description',
            field=models.TextField(blank=True, help_text='Functional description for this column: what it means, how it is edited (inline / dropdown / modal) and what it affects.'),
        ),
        migrations.AddField(
            model_name='inventorycolumn',
            name='short_label',
            field=models.CharField(blank=True, help_text="Short label for table header (e.g. 'R', 'S', 'B', 'RT'). If empty, the default human-readable name from FIELD_CHOICES is used.", max_length=32),
        ),
        migrations.AlterField(
            model_name='inventorycolumn',
            name='field_name',
            field=models.CharField(choices=[('rack', 'Rack'), ('shelf', 'Shelf'), ('box', 'Box'), ('group', 'Group (FK)'), ('name', 'Name'), ('part_description', 'Part Description'), ('part_number', 'Part Number'), ('dcm_number', 'DCM Number'), ('oem_name', 'OEM Name'), ('oem_number', 'OEM Number'), ('vendor', 'Vendor'), ('source_location', 'Source Location'), ('unit', 'Unit (FK)'), ('quantity_in_stock', 'Quantity in Stock'), ('price', 'Price'), ('reorder_level', 'Reorder Level'), ('reorder_time_days', 'Reorder Time in Days'), ('quantity_in_reorder', 'Quantity in Reorder'), ('condition_status', 'Condition Status'), ('discontinued', 'Discontinued'), ('verify', 'Verify / To Review'), ('favorite', 'User Favorite'), ('note', 'User Note'), ('for_reorder', 'For Reorder (computed)')], max_length=50, unique=True),
        ),
    ]
