# Generated by Django 5.2.8 on 2025-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorycolumn_full_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryimportexport',
            options={'verbose_name': 'Inventory import / export', 'verbose_name_plural': 'Inventory import / export'},
        ),
        migrations.AlterField(
            model_name='inventorycolumn',
            name='field_name',
            field=models.CharField(choices=[('location', 'Location (header)'), ('group', 'Group (FK)'), ('name', 'Name'), ('part_description', 'Part Description'), ('part_number', 'Part Number'), ('dcm_number', 'DCM Number'), ('oem_name', 'OEM Name'), ('oem_number', 'OEM Number'), ('vendor', 'Vendor'), ('source_location', 'Source Location'), ('unit', 'Unit (FK)'), ('quantity_in_stock', 'Quantity in Stock'), ('price', 'Price'), ('reorder_level', 'Reorder Level'), ('reorder_time_days', 'Reorder Time in Days'), ('quantity_in_reorder', 'Quantity in Reorder'), ('condition_status', 'Condition Status'), ('discontinued', 'Discontinued'), ('verify', 'Verify / To Review'), ('favorite', 'User Favorite'), ('note', 'User Note'), ('for_reorder', 'For Reorder (computed)')], max_length=50, unique=True),
        ),
    ]
