# Generated by Django 5.2.8 on 2025-12-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryimportexport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryimportexport',
            options={'verbose_name': 'Inventory import / export / delete', 'verbose_name_plural': 'Inventory import / export / delete'},
        ),
    ]
