# Generated by Django 5.2.8 on 2025-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryimportexport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_description',
            field=models.TextField(verbose_name='Part Description'),
        ),
    ]
