# Generated by Django 5.2.8 on 2025-12-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_part_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysettings',
            options={'verbose_name': 'Column Access', 'verbose_name_plural': 'Column Access'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'verbose_name': 'Group of Items', 'verbose_name_plural': 'Groups of Items'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit of Measure', 'verbose_name_plural': 'Units of Measure'},
        ),
    ]
